### ISSUE TITLE
2.7 Final Challenge

### ISSUE THREAD

**Issue by ghost** [codio-content/Python_Maze-Thinking_logically#2]
Passes with 'well done' even when no content in the py file
![finalchallenge](https://cloud.githubusercontent.com/assets/1127940/16413469/1075d262-3d2a-11e6-8e32-b241fe1de0e9.png)

**Comment by ksimuk** [comment]
fixed in https://github.com/codio-content/Python_Maze-Thinking_logically/pull/1
